name: Growthcraft Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup CI Workspace
      run: |
        chmod +x ./gradlew
        ./gradlew setupCIWorkspace -S
    - name: Build with Gradle
      run: ./gradlew build
    - name: List Artifacts
      run: ls -la ./build/libs
    - name: Release
      uses: docker://softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
